version: 1.0.{build}
cache: C:\Users\appveyor\.dnx\packages
before_build:
- cmd: dnu restore
build_script:
- cmd: dnu build src\Backend test\Backend.Test
test_script:
- cmd: dnx -p test/Backend.Test test
build:
  verbosity: normal